server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: stock-analysis-backend

  data:
    mongodb:
#      uri: mongodb://localhost:27017/stockAnalysis
      uri: mongodb+srv://tiwariabhishek22at:qbyBcDymdEPck6N4@stockanalysis.guhscse.mongodb.net/stockAnalysis?retryWrites=true&w=majority&ssl=true&tlsAllowInvalidCertificates=true
  jackson:
    time-zone: Asia/Kolkata
    date-format: yyyy-MM-dd HH:mm:ss

app:
  jwtSecret: bXlWZXJ5TG9uZ0FuZFNlY3VyZVNlY3JldEtleVRoYXRJc0F0TGVhc3QyNTZCaXRzTG9uZw==bXlWZXJ5TG9uZ0FuZFNlY3VyZVNlY3JldEtleVRoYXRJc0F0TGVhc3QyNTZCaXRzTG9uZw==
  jwtExpirationInMs: 604800000

logging:
  level:
    com.stockanalysis: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
